site_name: The Max Raphael Project
site_description: To commemorate the work of art historian and philosopher Max Raphael
site_url: http://www.maxraphael.org

theme:
    name: 'material'
    favicon: /assets/favicon.png
    logo:
        icon: 'library_books'
    palette:
        primary: 'indigo'
        accent: 'indigo'
        
markdown_extensions:
    - admonition
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.critic
    - pymdownx.tilde
    - pymdownx.mark
    - pymdownx.arithmatex
    - figureAltCaption

extra_css:
  - '/assets/css/magnific-popup.css'
  - '/assets/css/captions.css'
  
extra_javascript:
  - '//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'
  - 'assets/js/jquery.magnific-popup.min.js'
  - 'assets/js/popup.functions.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

repo_name: 'max-raphael-project'
repo_url: 'https://github.com/sammeltassen/mkdocs-base'

copyright: 'Copyright &copy; 2011 - 2018 The Max Raphael Project and the respective authors'

google_analytics:
  - 'UA-119145714-1'
  - 'auto'
  
nav:
    - Home: index.md
    - Biography: biography.md
    - Bibliography:
        - Primary: bibliography/primary.md
        - Secondary: bibliography/secondary.md
        - Archives: bibliography/archives.md
    - Resources:
        - Autobiography: resources/autobiography.md
        - Von Monet zu Picasso: resources/von-monet-zu-picasso.md
        - Raphaels 'erste Epoche': resources/raphaels-erste-epoche.md
        - Bison of uncertain sex: resources/bison-of-uncertain-sex.md
        - CÃ©zanne in the critical work of Max Raphael: resources/cezanne-in-the-critical-work.md
    - Contributors: project/contributors.md
    - Contact: project/contact.md